
import { intializeNodeContainer } from "./container.mjs"

var container = await intializeNodeContainer('speedtest')

const { waxEndpoint } = container.cradle

console.log(await waxEndpoint.speedtest([
  'https://wax.cryptolions.io',
  'https://wax.eosdac.io',
  'https://wax.eosrio.io',
  'https://atomic.wax.eosrio.io',
  'https://wax.eu.eosamsterdam.net',
  'https://wax-aa.eu.eosamsterdam.net',
  'https://api.waxsweden.org',
  'https://api.wax.alohaeos.com',
  'https://wax-atomic-api.eosphere.io',
  'https://wax.eosphere.io',
  'https://wax.eosusa.news',
  'https://wax.eosdsp.com',
  'https://wax.greymass.com',
  'https://wax.pink.gg',
  'https://wax.api.atomicassets.io',
  'https://api.wax.eosdetroit.io',
  'https://wax.eosn.io',
  'https://wax.dfuse.eosnation.io',
  'https://wax.firehose.eosnation.io',
  'https://api.wax.bountyblok.io',
  'https://api.wax-aa.bountyblok.io',
  'https://waxapi.ledgerwise.io',
  'https://atomic.ledgerwise.io',
  'https://publicapi-mainnet.eosauthority.com',
  'https://hyperion2.sentnl.io',
  'https://atomic.sentnl.io/',
  'https://api.hivebp.io',
  'https://api2.hivebp.io',
  'https://atomic.hivebp.io',
  'https://atomic2.hivebp.io',
  'https://wax.hivebp.io',
  'https://api-wax.eosarabia.net',
  'https://api-wax-aa.eosarabia.net',
  'https://apiwax.3dkrender.com',
  'https://query.3dkrender.com',
  'https://atomic.3dkrender.com',
  'https://api.wax.liquidstudios.io',
  'https://api.wax.liquidstudios.io/atomicassets',
  'https://wax-bp.wizardsguild.one',
  'https://wax-atomic.wizardsguild.one',
  'https://wax-history.wizardsguild.one',
  'https://wax.eosdublin.io',
  'https://wax-aa.eosdublin.io',
  'https://wax.dapplica.io',
  'https://aa.dapplica.io',
  'https://wax.hkeos.com',
  'https://wax.hkeos.com/aa',
  'https://api.waxeastern.cn',
  'https://api.wax.greeneosio.com',
  'https://api.atomic.greeneosio.com',
  'https://wax-mainnet.eosblocksmith.io',
  'https://wax.blokcrafters.io',
  'https://hyperblocks.pro',
  'https://wax-hyperion.eosiomadrid.io',
  'https://wax-atomic.eosiomadrid.io',
  'https://wax.blacklusion.io',
  'https://hyperion.wax.blacklusion.io',
  'https://aa.wax.blacklusion.io',
  'https://wax.eossweden.eu',
  'https://wax.eosasia.one',
  'https://wax.eoseoul.io',
  'https://wax.csx.io',
  'https://sslapi.teloscentral.com',
  'https://wax-public.neftyblocks.com',
  'https://aa-wax-public.neftyblocks.com',
  'https://api.niftylife.io',
  'https://waxapi.eoscannon.io',
  'https://api.oiac.io',
  'https://hyperion.oiac.io',
  'https://atomic.oiac.io/',
  'https://api.tokengamer.io',
  'https://atomic.tokengamer.io',
  'https://hyperion.tokengamer.io',
  'https://wax.eosio.cr',
  'https://api.nomadexchange.me',
  'https://api-wax-mainnet.wecan.dev',
  'https://hyperion-wax-mainnet.wecan.dev',
  'https://history-wax-mainnet.wecan.dev',
  'https://wax.darkprod.net/',
]))
